#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

# https://aka.ms/obpipelines/triggers
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - '*' 
    exclude:
    - 'Docs/*' 
    - 'README.md' 

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

parameters:
  - name: buildconfig
    displayName: Configuration to build
    type: string
    default: Release
    values:
    - Release  
    - Debug  

  - name: debug
    displayName: Enable debug output
    type: boolean
    default: false

  - name: push_nuget
    displayName: Push Nuget preview to aio-brokers
    type: boolean
    default: true

variables:
  - group: aio-connectors

  # Build pipeline template
  - name: BuildTemplate
    value: buddy

  # Configuration to build
  - name: BuildConfiguration
    value: ${{ parameters.buildconfig }}

  # Enable pipeline debug output
  - name: system.debug
    value: ${{ parameters.debug }}

  # Documentation on container image for jobs https://aka.ms/obpipelines/containers
  - name: WindowsContainerImage
    value: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest

  - name: LinuxContainerImage
    value: mcr.microsoft.com/onebranch/azurelinux/build:3.0

  # Control Nuget preview publishing
  - name: PushNugetPreview
    value: ${{ parameters.push_nuget }}

  # Control Nuget publishing
  - name: PushNuget
    value: false

extends:
  # https://aka.ms/obpipelines/templates
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates

  parameters:
    featureFlags:
      EnableCDPxPAT: false
      WindowsHostVersion:
        Version: 2022

    globalSdl:
      # https://aka.ms/obpipelines/sdl
      # https://eng.ms/docs/products/onebranch/securitycompliancegovernanceandpolicies/sdlforcontainerizedworkflows
      # https://eng.ms/docs/products/onebranch/securitycompliancegovernanceandpolicies/sdlforcontainerizedworkflows/customizesdlforcontainerbuilds
      antimalwareScan:
        enabled: true
      codeSignValidation:
        enabled: true
        break: true
      credscan:
        enabled: true
        break: true
      policheck:
        enabled: true
        break: true
      roslyn:
        enabled: true
        break: true
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
        break: true
      eslint:
        enabled: false
      armory:
        enabled: false
      apiscan:
        enabled: false
      bandit:
        enabled: false
      csrf:
        enabled: false
      spotbugs:
        enabled: false
      codeinspector:
        enabled: true
      codeql:
        compiled:
          enabled: true
          tsaEnabled: true
      prefast:
        enabled: false
      psscriptanalyzer:
        enabled: false
      tsa:
        enabled: true
      cg:
        failOnAlert: true
      sdtReport:
        enabled: true
      publishLogs:
        enabled: true
      sbom:
        enabled: false
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress

    git:
      fetchDepth: -1

    stages:
      - template: common-stages.yml@self
