name: Build and Test

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use
  CONFIGURATION: 'Release'
  FRAMEWORK: 'net6.0'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build-and-test:
    name: build-an-test-${{matrix.os}}-${{env.FRAMEWORK}}-${{env.CONFIGURATION}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]    

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Build
      run: dotnet build --force --framework ${{ env.FRAMEWORK }} --configuration ${{ env.CONFIGURATION }} "UA Core Library.sln"
      
    - name: Test
      run: dotnet test --no-build --framework ${{ env.FRAMEWORK }} --configuration ${{ env.CONFIGURATION }} /p:CollectCoverage=true --collect:"XPlat Code Coverage" --settings ./Tests/coverlet.runsettings.xml "UA Core Library.sln"
